### ISSUE TITLE
pandoc error in processing

### ISSUE THREAD

**Issue by gjb** [jrblevin/markdown-mode-guide#1]
I just cloned the git repo and ran make on a Debian 9.1 stretch system. The build output and error is shown below. Is this something expected, or have I missed a step?

$ make
cd manuscript && pandoc -S --highlight-style=tango -V geometry:"paperwidth=7in,paperheight=9.1in,margin=1in" --include-in-header=../preamble.tex --latex-engine=xelatex -o ../markdown-mode.pdf guide.txt
pandoc: Could not find image `http://link.url/image.jpg', skipping...
! Undefined control sequence.
l.1661 world\n

pandoc: Error producing PDF
Makefile:13: recipe for target 'markdown-mode.pdf' failed
make: *** [markdown-mode.pdf] Error 43

**Comment by jrblevin** [comment]
This was an early Make rule I used for quick local Previews using Pandoc.  Unfortunately, it no longer works since Pandoc doesn't recognize much of the Leanpub-specific syntax that is now used, so I'll remove it.  At this point, the full Leanpub toolchain is needed to produce a PDF.

The root issue is that some of the fenced code blocks with attributes aren't being processed as code blocks, and so some `\n` strings are making it through to LaTeX, which is trying to interpret them as macros, but they aren't.
